# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: NextJS starter app test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out Starter App QA Automation repo
      uses: actions/checkout@v2
      with:
          repository: contentstack/starter-apps-qa-automation
          token: ${{ secrets.aniket_test }}
          ref: Nextjs
         
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn test
